export const routeSelector = ({ app }) => app.route
export const loadingSelector = ({ app }) => app.loading
export const stickyHeaderSelector = ({ app }) => app.stickyHeader
export const typeSelector = ({ app }) => app.type
export const corporateSelector = ({ app }) => app.corporate
export const clientSelector = ({ app }) => app.client
export const autreClientSelector = ({ app }) => app.autreClient
export const covoiturageSelector = ({ app }) => app.covoiturage
export const annulerParSelector = ({ app }) => app.annulePar
export const raisonAnnulationSelector = ({ app }) => app.raisonAnnulation
export const pickupSelector = ({ app }) => app.pickup
export const agenceSelector = ({ app }) => app.agence
export const autrePickupSelector = ({ app }) => app.autrePickUp
export const destinationSelector = ({ app }) => app.destination
export const autreDestinationSelector = ({ app }) => app.autreDestination
export const kilometreSelector = ({ app }) => app.kilometre
export const dureeSelector = ({ app }) => app.duree
export const montantSelector = ({ app }) => app.montant
export const incidentSelector = ({ app }) => app.incident
export const typeIncidentSelector = ({ app }) => app.typeIncident
export const autreIncidentSelector = ({ app }) => app.autreIncident
export const commentaireSelector = ({ app }) => app.commentaire
export const dateDebutSelector = ({ app }) => app.dateDebut
export const timeSelector = ({ app }) => app.time